add android-7.0.0_r1 with android/platform/frameworks/base/android-7.0.0_r1 from https://android.googlesource.com, but rm the file for > 1M, e.g. bz2/mp3/wav/bmp/zip/ and so on

diff --git a/prebuilts/sdk/tools/jack b/prebuilts/sdk/tools/jack
--- a/prebuilts/sdk/tools/jack
+++ b/prebuilts/sdk/tools/jack
@@ -14,7 +14,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
-# Version: 1.1-mr2
+# Version: 1.3-a8
 #
 set -o nounset
 umask 077
@@ -22,92 +22,82 @@ umask 077
 #
 # Settings
 #
-LOCAL_SETTING="$HOME/.jack"
+JACK_VERSION=${JACK_VERSION:=3.36.CANDIDATE}
+JACK_HOME="${JACK_HOME:=$HOME/.jack-server}"
+CLIENT_SETTING="${CLIENT_SETTING:=$HOME/.jack-settings}"
 TMPDIR=${TMPDIR:=/tmp}
-SERVER_DIR=$TMPDIR/jack-$USER
+CLIENT_TMP_DIR=$TMPDIR/jack-$USER
+JACK_CONNECTION_TIMEOUT=300
+JACK_EXTRA_CURL_OPTIONS=${JACK_EXTRA_CURL_OPTIONS:=}
 
 #
-# Load local settings
+# Load client settings
 #
-source "$LOCAL_SETTING" 2>/dev/null
-
-#
-# Create or update local settings if needed
-#
-if [[ ! -f "$LOCAL_SETTING" || $SETTING_VERSION -lt 2 ]]; then
-  echo "Writing local settings in" $LOCAL_SETTING
-  cat >"$LOCAL_SETTING.$$" <<-EOT
-	# Server settings
-	SERVER=${SERVER:=true}
-	SERVER_PORT_SERVICE=${SERVER_PORT_SERVICE:=8072}
-	SERVER_PORT_ADMIN=${SERVER_PORT_ADMIN:=8073}
-	SERVER_COUNT=${SERVER_COUNT:=1}
-	SERVER_NB_COMPILE=${SERVER_NB_COMPILE:=4}
-	SERVER_TIMEOUT=${SERVER_TIMEOUT:=60}
-	SERVER_LOG=\${SERVER_LOG:=\$SERVER_DIR/jack-\$SERVER_PORT_SERVICE.log}
-	JACK_VM_COMMAND=\${JACK_VM_COMMAND:=java}
-	# Internal, do not touch
-	SETTING_VERSION=2
-EOT
-  ln -f "$LOCAL_SETTING.$$" "$LOCAL_SETTING"
-  rm "$LOCAL_SETTING.$$"
-  source "$LOCAL_SETTING"
+if [ -f "$CLIENT_SETTING" ]; then
+  source "$CLIENT_SETTING"
 fi
+
+#
+# Create or update client settings if needed
+#
+if [[ ! -f "$CLIENT_SETTING" || $SETTING_VERSION -lt 4 ]]; then
+  echo "Writing client settings in" $CLIENT_SETTING
+  cat >"$CLIENT_SETTING.$$" <<-EOT
+	# Server settings
+	SERVER_HOST=${SERVER_HOST:=127.0.0.1}
+	SERVER_PORT_SERVICE=${SERVER_PORT_SERVICE:=8076}
+	SERVER_PORT_ADMIN=${SERVER_PORT_ADMIN:=8077}
+
+	# Internal, do not touch
+	SETTING_VERSION=4
+EOT
+  ln -f "$CLIENT_SETTING.$$" "$CLIENT_SETTING"
+  rm "$CLIENT_SETTING.$$"
+  source "$CLIENT_SETTING"
+fi
+
+
+abort () { exit 255; }
+
+JACK_SERVER=${JACK_SERVER:=true}
+JACK_MAIN_COMMAND=${JACK_MAIN_COMMAND:="java -Djava.io.tmpdir=$TMPDIR -Dfile.encoding=UTF-8 -XX:+TieredCompilation"}
+JACK_REPOSITORY=${JACK_REPOSITORY:=}
+
 
 #
 # If not in server mode, exec jack
 #
-if [ "$SERVER" != "true" ]; then
-  exec $JACK_VM_COMMAND -cp $JACK_JAR com.android.jack.Main "$@"
-  echo "ERROR: Cannot succeed to launch Jack without Jack server" >&2
-  exit 255
+if [ "$JACK_SERVER" != "true" ]; then
+  if [ -z "$JACK_REPOSITORY" ]; then
+    echo "Running Jack without Jack server requires definition of JACK_REPOSITORY" >&2
+    abort
+  fi
+  JACK_JAR=$JACK_REPOSITORY/jack-$JACK_VERSION.jar
+  if [ ! -r "$JACK_JAR" ]; then
+    echo "Jack jar \"$JACK_JAR\" is not readable" >&2
+    abort
+  fi
+
+
+  exec $JACK_MAIN_COMMAND -jar $JACK_JAR "$@"
+  echo "Cannot succeed to launch Jack without Jack server" >&2
+  abort
 fi
 
-#
-# Static setting
-#
-SERVER_PRG="$JACK_VM_COMMAND -cp $JACK_JAR com.android.jack.server.JackSimpleServer"
 
 #
 # Prepare compilation
 #
-JACK_DIR="$SERVER_DIR/jack-task-$$/"
-JACK_OUT="$JACK_DIR/out"
-JACK_ERR="$JACK_DIR/err"
-JACK_CLI="$JACK_DIR/cli"
-JACK_EXIT="$JACK_DIR/exit"
 JACK_PWD="$PWD"
-
-mkdir "$SERVER_DIR" 2>/dev/null
+JACK_DIR="$CLIENT_TMP_DIR/jack-task-$$/"
+JACK_EXIT="$JACK_DIR/exit"
 
 # Cleanup
-trap 'rm -f "$JACK_OUT" "$JACK_ERR" "$JACK_CLI" "$JACK_EXIT" 2>>$SERVER_LOG; rmdir "$JACK_DIR" 2>>$SERVER_LOG' EXIT
+trap 'rm -f "$JACK_EXIT" 2>/dev/null; rmdir "$JACK_DIR";' EXIT
 
+mkdir "$CLIENT_TMP_DIR" 2>/dev/null || (exit 0)
 set -o errexit
-
-# Create fifos and files for a task
-rm -rf "$JACK_DIR"
-mkdir  "$JACK_DIR"
-mkfifo "$JACK_OUT"
-mkfifo "$JACK_ERR"
-touch  "$JACK_CLI" "$JACK_EXIT"
-
-# Try to cleanup if interrupted
-abort () { echo $(uptime) >>$SERVER_LOG; kill -9 $PID_OUT $PID_ERR 2>>$SERVER_LOG; wait $PID_OUT $PID_ERR 2>>$SERVER_LOG; exit 255; }
-trap 'abort' SIGHUP SIGINT SIGQUIT SIGTERM ERR
-
-# Redirect output and error
-cat <"$JACK_OUT" >&1 &
-PID_OUT=$!
-cat <"$JACK_ERR" >&2 &
-PID_ERR=$!
-
-# Prepare the working directory and command line
-echo -n \"$PWD\" "" >"$JACK_CLI"
-for i in "$@"; do
-  echo -n \"$i\" "" >>"$JACK_CLI"
-done
-echo >>"$JACK_CLI"
+mkdir "$JACK_DIR"
 
 #
 # Launch the compilation
@@ -116,69 +106,72 @@ echo >>"$JACK_CLI"
 set +o errexit
 trap ERR
 
-RETRY_LAUNCH=1
-RETRY_SESSION=3
-DELAY_CONNECT=30
-
-
-# Launch compilation
-DATE_CONNECT=$(date +%s)
-while true; do
-  CURL_TIME=$(date +%H:%M:%S)
-  HTTP_CODE=$(curl --fail --silent --data @- --output "$JACK_EXIT" --write-out %{http_code} --connect-timeout 10 --no-proxy 127.0.0.1:$SERVER_PORT_SERVICE http://127.0.0.1:$SERVER_PORT_SERVICE/jack <<< "+ $JACK_OUT $JACK_ERR $JACK_CLI")
-  CURL_CODE=$?
-  JACK_CODE=$(cat "$JACK_EXIT")
-  echo "CURL: $$ - $CURL_TIME - $CURL_CODE - $HTTP_CODE - $JACK_CODE" >>$SERVER_LOG
-  if [ $CURL_CODE -eq 0 ]; then
-    # No problem, let's go
-    break;
-  elif [ $CURL_CODE -eq 7 ]; then
-    # Failed to connect
-    if [ $(date +%s) -ge $DATE_CONNECT ]; then
-      if [ $RETRY_LAUNCH -eq 0 ]; then
-        echo "ERROR: Cannot launch Jack server" >&2
-        abort
-      else
-        let RETRY_LAUNCH=RETRY_LAUNCH-1
-        echo "Launching background server" $SERVER_PRG
-        $SERVER_PRG $SERVER_PORT_SERVICE $SERVER_PORT_ADMIN $SERVER_COUNT $SERVER_NB_COMPILE $SERVER_TIMEOUT >>$SERVER_LOG 2>&1 &
-        # New server, let's try a bit to connect
-        let DATE_CONNECT=$(date +%s)+$DELAY_CONNECT;
-      fi
-    else
-      sleep 0.2 2>/dev/null
-    fi
-    # Trying with a new connection, let's retry session 3 times max
-    RETRY_SESSION=3
-  elif  [ $CURL_CODE -eq 22 ]; then
-    # Http code not OK, let's decode and abort
-    if [ $HTTP_CODE -eq 401 ]; then
-      # 401: Unauthorized
-      echo "ERROR: Security problem, see Jack server log ($SERVER_LOG)" >&2
-      abort
-    elif [ $HTTP_CODE -eq 400 ]; then
-      # 400: Bad request
-      echo "ERROR: Bad request, see Jack server log ($SERVER_LOG)" >&2
-      abort
-    else
-      # Other
-      echo "ERROR: Internal unknown error ($HTTP_CODE), try other ports in ~/.jack, or see Jack server log ($SERVER_LOG)" >&2
-      abort
-    fi
-  else
-    # In case of partial, timeout, empty respond, network error, let's retry
-    if [ $RETRY_SESSION -eq 0 ]; then
-      echo "ERROR: Communication error with Jack server ($CURL_CODE)" >&2
-      abort
-    else
-      let RETRY_SESSION=RETRY_SESSION-1
-    fi
-  fi
+# put arguments in a non array variable
+ARGS=""
+for i in "$@"; do
+  ARGS="$ARGS $i"
 done
 
-# Wait for termination
-wait $PID_OUT
-wait $PID_ERR
 
-# Exit
-exit $JACK_CODE
+CURRENT_CHARSET=$(locale charmap)
+if [ -z "$CURRENT_CHARSET" ]; then
+  CHARSET_ARGUMENT=
+else
+  CHARSET_ARGUMENT=";charset=$CURRENT_CHARSET"
+fi
+
+# Launch compilation
+exec 3>&1
+exec 4>&2
+HTTP_CODE=$(curl -f $JACK_EXTRA_CURL_OPTIONS \
+     --cert "${JACK_HOME}/client.pem" \
+     --cacert "${JACK_HOME}/server.pem" \
+     --output >(tee >(sed -n -e 's/^E|\(.*\)$/\1/p' >&4 ) | tee >(sed -n -e 's/^X|\(.*\)$/\1/p' >$JACK_EXIT) | sed -n -e 's/^O|\(.*\)$/\1/p' >&3) \
+     --no-buffer --write-out '%{http_code}' --silent --connect-timeout $JACK_CONNECTION_TIMEOUT \
+     -X POST \
+     -H "Accept: application/vnd.jack.command-out;version=1;charset=$CURRENT_CHARSET" \
+     -F "cli=$ARGS;type=text/plain;charset=$CURRENT_CHARSET" \
+     -F "version=$JACK_VERSION;type=application/vnd.jack.select-exact;version=1" \
+     -F "pwd=$JACK_PWD;type=text/plain$CHARSET_ARGUMENT" \
+     --noproxy ${SERVER_HOST} \
+     https://${SERVER_HOST}:$SERVER_PORT_SERVICE/jack \
+     )
+
+CURL_CODE=$?
+exec 3>&-
+exec 4>&-
+JACK_CODE=$(cat "$JACK_EXIT")
+if [ $CURL_CODE -eq 0 ]; then
+  # No problem, let's go
+  exit $JACK_CODE
+elif [ $CURL_CODE -eq 7 ]; then
+  # Failed to connect
+  echo "No Jack server running. Try 'jack-admin start-server'" >&2
+  abort
+elif [ $CURL_CODE -eq 35 ]; then
+  echo "SSL error when connecting to the Jack server. Try 'jack-diagnose'" >&2
+  abort
+elif [ $CURL_CODE -eq 58 ]; then
+  echo "Failed to contact Jack server: Problem reading ${JACK_HOME}/client.pem. Try 'jack-diagnose'" >&2
+  abort
+elif [ $CURL_CODE -eq 60 ]; then
+  echo "Failed to authenticate Jack server certificate. Try 'jack-diagnose'" >&2
+  abort
+ elif [ $CURL_CODE -eq 77 ]; then
+  echo "Failed to contact Jack server: Problem reading ${JACK_HOME}/server.pem. Try 'jack-diagnose'" >&2
+  abort
+elif  [ $CURL_CODE -eq 22 ]; then
+  # Http code not OK, let's decode and abort
+  if [ $HTTP_CODE -eq 400 ]; then
+    # 400: Bad request
+    echo "Bad request, see server log" >&2
+    abort
+  else
+    # Other
+    echo "Internal unknown error ($HTTP_CODE), try 'jack-diagnose' or see Jack server log" >&2
+    abort
+  fi
+else
+  echo "Communication error with Jack server ($CURL_CODE). Try 'jack-diagnose'" >&2
+  abort
+fi
